const colleges = [
  {
    name: 'IIT Madras',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'NIRF 2025'],
    location: 'Chennai, Tamil Nadu',
    intro: 'Flagship IIT with strong academics, research, startups and national prestige.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Extremely high for top branches.',
    difficulty: 10,
    review: 4.9,
    skills: 'Core engineering, research, problem-solving, innovation.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'NIRF 2025 Engineering'
  },
  {
    name: 'IIT Delhi',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Top tier'],
    location: 'New Delhi, Delhi',
    intro: 'Premier IIT known for excellent academics, research and strong industry exposure.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Extremely high.',
    difficulty: 10,
    review: 4.9,
    skills: 'Engineering depth, research, leadership, startup culture.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Bombay',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Top tier'],
    location: 'Mumbai, Maharashtra',
    intro: 'Highly preferred IIT with strong placements, coding culture and entrepreneurial ecosystem.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Extremely high.',
    difficulty: 10,
    review: 4.9,
    skills: 'Tech, analytics, innovation, peer learning.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Kanpur',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Research'],
    location: 'Kanpur, Uttar Pradesh',
    intro: 'Known for rigorous academics, strong science base and research culture.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 10,
    review: 4.8,
    skills: 'Analytical thinking, technical depth, research.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Kharagpur',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Large campus'],
    location: 'Kharagpur, West Bengal',
    intro: 'Historic IIT with diverse departments, large campus and strong alumni network.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 10,
    review: 4.8,
    skills: 'Technical foundations, leadership, broad exposure.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Roorkee',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Historic'],
    location: 'Roorkee, Uttarakhand',
    intro: 'Strong engineering institute with excellent civil, core and tech reputation.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Engineering fundamentals, research, design.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Guwahati',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Fast rising'],
    location: 'Guwahati, Assam',
    intro: 'Major IIT known for good academics, scenic campus and strong coding culture.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Engineering, research, tech culture.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Hyderabad',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Modern'],
    location: 'Hyderabad, Telangana',
    intro: 'Modern IIT with strong emphasis on innovation, AI, design and research.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Emerging tech, innovation, interdisciplinary work.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT BHU Varanasi',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'BHU'],
    location: 'Varanasi, Uttar Pradesh',
    intro: 'Strong engineering institute combining IIT brand with BHU legacy.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.7,
    skills: 'Engineering knowledge, coding, peer learning.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Dhanbad (ISM)',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'ISM'],
    location: 'Dhanbad, Jharkhand',
    intro: 'Known historically for mining and earth sciences, now broad engineering strength too.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High to very high.',
    difficulty: 9,
    review: 4.7,
    skills: 'Engineering, domain specialization, analytics.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Indore',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Research'],
    location: 'Indore, Madhya Pradesh',
    intro: 'Smaller IIT with strong academic focus and growing research output.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 9,
    review: 4.7,
    skills: 'Research, scientific thinking, engineering basics.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'Top IIT'
  },
  {
    name: 'IIT Ropar',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Growing'],
    location: 'Rupnagar, Punjab',
    intro: 'Fast-growing IIT with strong academics and improving research visibility.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 9,
    review: 4.6,
    skills: 'Engineering, research, innovation.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'NIRF 2025 ranked IIT'
  },
  {
    name: 'IIT Mandi',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Himachal'],
    location: 'Mandi, Himachal Pradesh',
    intro: 'Growing IIT with strong student culture and good research direction.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.6,
    skills: 'Core engineering, project work, innovation.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'NIRF 2025 ranked IIT'
  },
  {
    name: 'IIT Jodhpur',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Emerging'],
    location: 'Jodhpur, Rajasthan',
    intro: 'Emerging IIT with focus on technology, research and interdisciplinary areas.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.6,
    skills: 'Tech, innovation, research.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'NIRF 2025 ranked IIT'
  },
  {
    name: 'IIT Gandhinagar',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Modern'],
    location: 'Gandhinagar, Gujarat',
    intro: 'Modern IIT known for flexible academics and interdisciplinary culture.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.6,
    skills: 'Engineering, critical thinking, research.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'IIT'
  },
  {
    name: 'IIT Patna',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Growing'],
    location: 'Patna, Bihar',
    intro: 'Established newer IIT with strong core and tech branches.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.5,
    skills: 'Engineering foundations, coding, projects.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'IIT'
  },
  {
    name: 'IIT Bhubaneswar',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&w=1200&q=80',
    tags: ['IIT', 'Engineering', 'Odisha'],
    location: 'Bhubaneswar, Odisha',
    intro: 'Newer IIT with steady academic and research growth.',
    eligibility: '12th PCM; JEE Main; JEE Advanced; JoSAA counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.5,
    skills: 'Engineering, research, interdisciplinary learning.',
    path: 'JEE Main → JEE Advanced → JoSAA',
    rankLabel: 'IIT'
  },

  {
    name: 'AIIMS New Delhi',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'NIRF 2025'],
    location: 'New Delhi, Delhi',
    intro: 'India’s most prestigious medical institute with top academic and clinical exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Extremely high.',
    difficulty: 10,
    review: 4.9,
    skills: 'Clinical medicine, academic rigor, research, high patient load exposure.',
    path: 'NEET UG → MCC/AIQ counselling',
    rankLabel: 'NIRF 2025 Medical'
  },
  {
    name: 'AIIMS Rishikesh',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Top medical'],
    location: 'Rishikesh, Uttarakhand',
    intro: 'One of the strongest newer AIIMS with good academics and tertiary care exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Clinical reasoning, academics, patient care.',
    path: 'NEET UG → counselling',
    rankLabel: 'NIRF 2025 ranked AIIMS'
  },
  {
    name: 'AIIMS Bhubaneswar',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Top medical'],
    location: 'Bhubaneswar, Odisha',
    intro: 'Strong AIIMS campus with good medical training and patient exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Clinical medicine, disciplined study, tertiary care exposure.',
    path: 'NEET UG → counselling',
    rankLabel: 'NIRF 2025 ranked AIIMS'
  },
  {
    name: 'AIIMS Jodhpur',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Rajasthan'],
    location: 'Jodhpur, Rajasthan',
    intro: 'Well-regarded AIIMS with growing academic and clinical strength.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.7,
    skills: 'Clinical skills, medicine, hospital practice.',
    path: 'NEET UG → counselling',
    rankLabel: 'NIRF 2025 ranked AIIMS'
  },
  {
    name: 'AIIMS Bhopal',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Madhya Pradesh'],
    location: 'Bhopal, Madhya Pradesh',
    intro: 'Established AIIMS with solid academics and tertiary care exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.7,
    skills: 'Patient care, academics, hospital systems.',
    path: 'NEET UG → counselling',
    rankLabel: 'NIRF 2025 ranked AIIMS'
  },
  {
    name: 'AIIMS Patna',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Bihar'],
    location: 'Patna, Bihar',
    intro: 'Important government medical institute with growing patient load and academics.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High to very high.',
    difficulty: 8,
    review: 4.5,
    skills: 'Clinical medicine, patient handling, theory-to-practice.',
    path: 'NEET UG → counselling',
    rankLabel: 'NIRF 2025 ranked AIIMS'
  },
  {
    name: 'AIIMS Raipur',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Chhattisgarh'],
    location: 'Raipur, Chhattisgarh',
    intro: 'Growing AIIMS with government medical training and clinical exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High to very high.',
    difficulty: 8,
    review: 4.5,
    skills: 'Clinical work, academics, public health perspective.',
    path: 'NEET UG → counselling',
    rankLabel: 'AIIMS'
  },
  {
    name: 'AIIMS Raebareli',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1581595219315-a187dd40c322?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'UP'],
    location: 'Raebareli, Uttar Pradesh',
    intro: 'Functional AIIMS under PMSSY with MBBS and hospital services.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.4,
    skills: 'Clinical foundation, medical academics.',
    path: 'NEET UG → counselling',
    rankLabel: 'AIIMS'
  },
  {
    name: 'AIIMS Nagpur',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'Maharashtra'],
    location: 'Nagpur, Maharashtra',
    intro: 'Newer AIIMS with active MBBS and hospital operations.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.4,
    skills: 'Medical training, patient care.',
    path: 'NEET UG → counselling',
    rankLabel: 'AIIMS'
  },
  {
    name: 'AIIMS Kalyani',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1587351021759-3e566b3db4f1?auto=format&fit=crop&w=1200&q=80',
    tags: ['AIIMS', 'Medicine', 'West Bengal'],
    location: 'Kalyani, West Bengal',
    intro: 'Newer AIIMS with growing infrastructure and MBBS training.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.4,
    skills: 'Clinical basics, academics.',
    path: 'NEET UG → counselling',
    rankLabel: 'AIIMS'
  },

  {
    name: 'Christian Medical College Vellore',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
    tags: ['Medical', 'Private', 'Top'],
    location: 'Vellore, Tamil Nadu',
    intro: 'Highly respected medical college known for academics and hospital quality.',
    eligibility: '10+2 PCB; NEET UG; institute process as applicable.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Clinical excellence, ethics, academic rigor.',
    path: 'NEET UG → admission process',
    rankLabel: 'Top medical college'
  },
  {
    name: 'PGIMER Chandigarh',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80',
    tags: ['Medical', 'PGIMER', 'Prestige'],
    location: 'Chandigarh',
    intro: 'Premier postgraduate medical and research institute with strong clinical reputation.',
    eligibility: 'Best known for postgraduate pathways; undergraduate visibility on your site can be marked accordingly.',
    cutoff: 'Highly competitive.',
    difficulty: 9,
    review: 4.8,
    skills: 'Clinical specialization, research, tertiary care exposure.',
    path: 'Primarily postgraduate-focused institute',
    rankLabel: 'NIRF 2025 Medical'
  },
  {
    name: 'JIPMER Puducherry',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=1200&q=80',
    tags: ['Medical', 'JIPMER', 'Top govt'],
    location: 'Puducherry',
    intro: 'Top government medical institute with strong academics and patient care exposure.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Clinical medicine, academics, practical exposure.',
    path: 'NEET UG → counselling',
    rankLabel: 'Top government medical college'
  },
  {
    name: 'Banaras Hindu University (IMS-BHU)',
    country: 'India',
    stream: 'Medicine',
    image: 'https://images.unsplash.com/photo-1542736667-069246bdbc74?auto=format&fit=crop&w=1200&q=80',
    tags: ['Medical', 'BHU', 'Government'],
    location: 'Varanasi, Uttar Pradesh',
    intro: 'Large legacy medical institute with strong government-sector reputation.',
    eligibility: '10+2 PCB; NEET UG; counselling.',
    cutoff: 'High to very high.',
    difficulty: 8,
    review: 4.6,
    skills: 'Clinical medicine, academics, patient handling.',
    path: 'NEET UG → counselling',
    rankLabel: 'Top medical'
  },

  {
    name: 'NLSIU Bengaluru',
    country: 'India',
    stream: 'Law',
    image: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=1200&q=80',
    tags: ['Law', 'CLAT', 'Top law'],
    location: 'Bengaluru, Karnataka',
    intro: 'One of the most preferred law schools in India with strong placements and policy exposure.',
    eligibility: '10+2; CLAT UG.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Legal reasoning, writing, research, communication.',
    path: 'CLAT UG → counselling',
    rankLabel: 'Top law school'
  },
  {
    name: 'NLU Delhi',
    country: 'India',
    stream: 'Law',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80',
    tags: ['Law', 'AILET', 'Top law'],
    location: 'New Delhi, Delhi',
    intro: 'Premier national law university with separate AILET-based admission.',
    eligibility: '10+2; AILET.',
    cutoff: 'Very high.',
    difficulty: 9,
    review: 4.8,
    skills: 'Legal analysis, policy, research, advocacy.',
    path: 'AILET → admission',
    rankLabel: 'Top law school'
  },
  {
    name: 'IIM Ahmedabad',
    country: 'India',
    stream: 'Management',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    tags: ['MBA', 'CAT', 'Top management'],
    location: 'Ahmedabad, Gujarat',
    intro: 'Flagship management institute with elite peer group and strong placements.',
    eligibility: 'Bachelor’s degree; CAT; interview process.',
    cutoff: 'Very high CAT percentile.',
    difficulty: 9,
    review: 4.8,
    skills: 'Leadership, business thinking, communication.',
    path: 'Graduate → CAT → shortlist → interview',
    rankLabel: 'Top IIM'
  },
  {
    name: 'IIM Bangalore',
    country: 'India',
    stream: 'Management',
    image: 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&q=80',
    tags: ['MBA', 'CAT', 'Top management'],
    location: 'Bengaluru, Karnataka',
    intro: 'Top business school with strong industry links and excellent placements.',
    eligibility: 'Bachelor’s degree; CAT; interview process.',
    cutoff: 'Very high CAT percentile.',
    difficulty: 9,
    review: 4.8,
    skills: 'Management, strategy, analytics, leadership.',
    path: 'Graduate → CAT → shortlist → interview',
    rankLabel: 'Top IIM'
  },
  {
    name: 'BITS Pilani',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Engineering', 'BITSAT', 'Private top'],
    location: 'Pilani, Rajasthan',
    intro: 'Highly respected private engineering institution with strong academics and placements.',
    eligibility: '12th PCM; BITSAT.',
    cutoff: 'High.',
    difficulty: 8,
    review: 4.7,
    skills: 'Engineering, coding, entrepreneurship.',
    path: 'BITSAT → counselling',
    rankLabel: 'Top private engineering'
  },
  {
    name: 'VIT Vellore',
    country: 'India',
    stream: 'Engineering',
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
    tags: ['Engineering', 'VITEEE', 'Private'],
    location: 'Vellore, Tamil Nadu',
    intro: 'Popular private engineering university with wide branch options and strong placement visibility.',
    eligibility: '12th PCM; VITEEE or other approved route.',
    cutoff: 'Competitive.',
    difficulty: 7,
    review: 4.4,
    skills: 'Engineering, placements preparation, project work.',
    path: 'VITEEE → counselling',
    rankLabel: 'Top private engineering'
  }
];

const exams = [
  {
    name: 'JEE Main',
    forWhom: 'NITs, IIITs, many engineering colleges, and JEE Advanced eligibility',
    details: 'Main national engineering entrance exam testing PCM speed, accuracy and concept clarity.',
    difficulty: 'High',
    route: 'JEE Main → NIT/IIIT counselling or JEE Advanced eligibility'
  },
  {
    name: 'JEE Advanced',
    forWhom: 'IIT admissions',
    details: 'Second-stage exam for IIT entry. More conceptually demanding than JEE Main.',
    difficulty: 'Very high',
    route: 'JEE Main qualification → JEE Advanced → JoSAA'
  },
  {
    name: 'NEET UG',
    forWhom: 'MBBS, BDS and allied medical admissions',
    details: 'National medical entrance exam focused on PCB with high competition and speed pressure.',
    difficulty: 'Very high',
    route: 'NEET UG → AIQ/State counselling'
  },
  {
    name: 'INI-CET',
    forWhom: 'Postgraduate medical admission in select INIs',
    details: 'Important postgraduate medical entrance for institutes like AIIMS, JIPMER, PGIMER and NIMHANS pathways as applicable.',
    difficulty: 'Very high',
    route: 'MBBS → internship/eligibility → INI-CET'
  },
  {
    name: 'NEET PG',
    forWhom: 'MD, MS, PG Diploma pathways',
    details: 'National postgraduate medical entrance with vast syllabus and rank-sensitive counselling.',
    difficulty: 'Very high',
    route: 'MBBS → internship/eligibility → NEET PG → counselling'
  },
  {
    name: 'CLAT UG',
    forWhom: 'NLUs and law aspirants',
    details: 'Law entrance focused on reading comprehension, reasoning, legal aptitude style thinking and current affairs.',
    difficulty: 'High',
    route: 'CLAT → counselling'
  },
  {
    name: 'AILET',
    forWhom: 'NLU Delhi',
    details: 'Separate entrance for National Law University Delhi.',
    difficulty: 'High',
    route: 'AILET → NLU Delhi admission'
  },
  {
    name: 'CAT',
    forWhom: 'IIMs and other MBA institutes',
    details: 'MBA entrance focused on aptitude, LRDI, VARC and percentile strategy.',
    difficulty: 'High',
    route: 'CAT → shortlist → interview/WAT'
  },
  {
    name: 'BITSAT',
    forWhom: 'BITS campuses',
    details: 'Computer-based engineering entrance exam for BITS institutions.',
    difficulty: 'High',
    route: 'BITSAT → counselling'
  },
  {
    name: 'VITEEE',
    forWhom: 'VIT admissions',
    details: 'Private university engineering entrance exam used for VIT campuses.',
    difficulty: 'Moderate to high',
    route: 'VITEEE → counselling'
  },
  {
    name: 'CUET UG',
    forWhom: 'Central universities and many undergraduate programs',
    details: 'Common university entrance for many non-engineering and multidisciplinary UG admissions.',
    difficulty: 'Moderate to high',
    route: 'CUET UG → university counselling'
  },
  {
    name: 'NDA',
    forWhom: 'Defence aspirants after 12th',
    details: 'For candidates seeking entry into National Defence Academy after school.',
    difficulty: 'High',
    route: 'NDA written exam → SSB → medicals'
  }
];
